import jsPDF from "jspdf";

export const downloadAadharPDF = () => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  const W = 210, ml = 15, mr = 195;

  // Border
  doc.setDrawColor(0);
  doc.setLineWidth(1);
  doc.rect(8, 8, W - 16, 279);

  // Header
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Aadhar Card Print", W / 2, 20, { align: "center" });

  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text("Generated by SevaZone | Support: +91 8307950410", W / 2, 285, { align: "center" });

  doc.save("aadhar_print.pdf");
};
