// haryanaDomicilePdf.ts
import jsPDF from "jspdf";

export const downloadHaryanaDomicilePDF = (data: any) => {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210, ml = 15, mr = 195;

  // Border (orange double)
  doc.setDrawColor(220, 100, 20);
  doc.setLineWidth(4);
  doc.rect(6, 6, W - 12, 285);
  doc.setLineWidth(1);
  doc.rect(10, 10, W - 20, 277);

  // Top IDs (you can add logos/images here)
  doc.setFillColor(0, 100, 200);
  doc.rect(ml, 15, 45, 8, "F");
  doc.setTextColor(255);
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.text("Family Id", ml + 2, 20);
  doc.text("5BEN2025876", ml + 18, 20);

  doc.setFillColor(0, 100, 200);
  doc.rect(mr - 55, 15, 45, 8, "F");
  doc.text("eDisHa", mr - 53, 20);
  doc.text("0197157275", mr - 38, 20);

  // Title
  doc.setTextColor(220, 100, 20);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Government of Haryana", W / 2, 40, { align: "center" });
  doc.setFontSize(20);
  doc.setTextColor(0, 0, 0);
  doc.text("Haryana Resident Certificate", W / 2, 55, { align: "center" });

  // Photo
  if (data.photo) {
    try { doc.addImage(data.photo, "JPEG", 155, 65, 35, 42); } catch (e) {}
  } else {
    doc.setDrawColor(200, 150, 50);
    doc.setLineWidth(0.5);
    doc.rect(155, 65, 35, 42);
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text("Photo", 167, 88);
  }

  // Body text
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(0, 0, 0);
  const body = `Certified that Mr./Mrs. ${data.name || "_____"} s/o Sh. ${data.father || "_____"} resident of H.No.- ${data.house || "_____"} ,Landmark- ${data.landmark || "_____"} , Vill/Town- ${data.vill || "_____"}, District- ${data.district || "_____"}, Pin- ${data.pin || "_____"}, Town- ${data.town || "_____"}, Tehsil- ${data.tahsil || "_____"}, District- ${data.district || "_____"} was born or residing in Haryana State as verified by Tehsildar.`;
  const lines = doc.splitTextToSize(body, 130);
  doc.text(lines, ml, 75);

  // Validity
  let y = 130;
  doc.setFontSize(10);
  const validity = "The validity of Resident Certificate shall be as long as the holder of this certificate maintains his residential address in Haryana State Instructions No. 22/28/2003- 3GS-III, dated 30-1-2004.";
  doc.text(doc.splitTextToSize(validity, mr - ml), ml, y);
  y += 30;

  // Issued by
  doc.setFont("helvetica", "italic");
  doc.text("Issued by:", mr - 40, y);
  y += 20;

  // Footer
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`No.: HR/${new Date().getFullYear()}/${Math.floor(Math.random() * 9999)}`, ml, y + 20);
  doc.text(`Date : ${new Date().toLocaleDateString("en-IN")}`, ml, y + 27);
  doc.text(`Place: ${data.town || ""}`, ml, y + 34);
  doc.setFont("helvetica", "bold");
  doc.text(`Tehsildar, ${data.district || ""}`, mr - 20, y + 27, { align: "right" });

  y += 50;
  doc.setLineWidth(0.3);
  doc.line(ml, y, mr, y);
  y += 8;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(80);
  doc.text(
    "This certificate is electronically generated and authenticity of this certificate can be verified from http://edisha.gov.in",
    ml,
    y,
    { maxWidth: mr - ml }
  );
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by SevaZone | Support: +91 8307950410", W / 2, 285, { align: "center" });

  doc.save("haryana_resident.pdf");
};
